project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"

website:
  title: "Analyse Statistique des Données Mondiales de Suicide "
  site-url: "https://amenijawadi.github.io/analyse_suicide/"
  repo-url: "https://github.com/amenijawadi/analyse_suicide"
  
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Projects
        contents:
          - text: "Exploration des Données"
            file: qmd/01_exploration.qmd
          - text: "Nettoyage des Données"
            file: qmd/02_nettoyage.qmd
          - text: "Analyse Temporelle"
            file: qmd/03_analyse_temporelle.qmd
          - text: "Analyse par sexe"
            file: qmd/04_analyse_sexe.qmd
          - text: "Distributions Fruits"
            file: qmd/05-distributions-fruits-tidyverse.qmd
          - text: "Tests Statistiques"
            file: qmd/test_stat.qmd
      - section: Presentations
        contents:
          - text: "Tests Classiques"
            file: qmd/06-classical-tests.qmd

format:
  html:
    theme: light
    css: thpe.css
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Show code"
    code-link: true
    code-overflow: scroll
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
    papersize: a4
    geometry:
      - top=20mm
      - left=25mm
      - bottom=25mm

# Configuration WebR (R seulement)
webr:
  packages: ["dplyr", "ggplot2", "readxl", "tidyr", "lubridate", "car", "lmtest"]

execute:
  freeze: true
  cache: false
  echo: false
  warning: false
  message: false
  engine: r  # ← FORCER l'utilisation de R seulement

# DÉSACTIVER Jupyter
kernel:
  jupyter: false

bibliography: bib.bib
csl: apa.csl

latex-auto-install: true